Built revised makefile for docker image...

diff --git a/.docker/Dockerfile b/.docker/Dockerfile
--- a/.docker/Dockerfile
+++ b/.docker/Dockerfile
@@ -1,7 +1,20 @@
-FROM node:lts AS runtime
+FROM node:lts-alpine AS base
+
+FROM base AS deps
+RUN apk add --no-cache libc6-compat
 WORKDIR /usr/src/app
+COPY package.json yarn.lock* package-lock.json* pnpm-lock.yaml* .npmrc ./
+RUN \
+  if [ -f yarn.lock ]; then yarn --frozen-lockfile; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then yarn global add pnpm && pnpm install -P --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
+
+FROM base AS runner
+WORKDIR /usr/src/app
+COPY --from=deps /usr/src/app/node_modules ./node_modules
 COPY . .
-RUN npm install --omit=dev
 ENV HOST=0.0.0.0
 ENV PORT=3000
 EXPOSE 3000
